{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Windows10\\.conda\\envs\\Instalaciones\\lib\\tkinter\\__init__.py\", line 1702, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 24, in actualizar_filtro\n",
      "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
      "  File \"<ipython-input-10-7d3b513890fa>\", line 14, in aplicar_filtro_gaussiano\n",
      "    return cv2.GaussianBlur(image, (size, size), 0)\n",
      "cv2.error: OpenCV(3.4.2) C:\\Miniconda3\\conda-bld\\opencv-suite_1534379934306\\work\\modules\\imgproc\\src\\smooth.cpp:3818: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import tkinter as tk\n",
    "from PIL import Image, ImageTk\n",
    "import numpy as np\n",
    "import cv2\n",
    "\n",
    "\n",
    "def escalar_imagen(image, max_width):\n",
    "    original_height, original_width = image.shape\n",
    "    ratio = max_width / original_width\n",
    "    height = int(original_height * ratio)\n",
    "    return cv2.resize(image, (max_width, height))\n",
    "\n",
    "def aplicar_filtro_gaussiano(image, size):\n",
    "    return cv2.GaussianBlur(image, (size, size), 0)\n",
    "\n",
    "def mostrar_imagen(image, label, max_width):\n",
    "    imagen_resized = escalar_imagen(image, max_width)\n",
    "    imagen_tk = ImageTk.PhotoImage(image=Image.fromarray(imagen_resized))\n",
    "    label.config(image=imagen_tk)\n",
    "    label.image = imagen_tk\n",
    "\n",
    "def actualizar_filtro(valor):\n",
    "    size = int(valor)\n",
    "    imagen_filtrada = aplicar_filtro_gaussiano(img, size)\n",
    "    \n",
    "    mostrar_imagen(img, label_imagen, 300)\n",
    "    mostrar_imagen(imagen_filtrada, label_g_real, 300)\n",
    "    \n",
    "    # Muestra la matriz del filtro frecuencial (opcional)\n",
    "    filtro_frecuencial = np.fft.fftshift(np.fft.fft2(imagen_filtrada))\n",
    "    filtro_frecuencial_magnitud = np.abs(filtro_frecuencial)\n",
    "    mostrar_imagen(filtro_frecuencial_magnitud, label_matriz, 300)\n",
    "\n",
    "# Ruta de la imagen a mostrar\n",
    "image_path = \"scarlet.jpg\"\n",
    "img = cv2.imread(image_path, 0)\n",
    "\n",
    "ventana = tk.Tk()\n",
    "ventana.title(\"Filtro Gaussiano con Tkinter\")\n",
    "\n",
    "label_imagen = tk.Label(ventana)\n",
    "mostrar_imagen(img, label_imagen, 300)\n",
    "label_imagen.grid(row=0, column=0, padx=10, pady=10)\n",
    "\n",
    "label_matriz = tk.Label(ventana)\n",
    "label_matriz.grid(row=0, column=1, padx=10, pady=10)\n",
    "\n",
    "label_g_real = tk.Label(ventana)\n",
    "label_g_real.grid(row=0, column=2, padx=10, pady=10)\n",
    "\n",
    "slider_n = tk.Scale(ventana, from_=1, to=30, orient=tk.HORIZONTAL,\n",
    "                    label=\"Tamaño del filtro\", command=actualizar_filtro)\n",
    "slider_n.set(2)\n",
    "slider_n.grid(row=1, column=0, columnspan=3, pady=10)\n",
    "\n",
    "ventana.mainloop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
